import Navbar from "@/components/Navbar";
import "./globals.css";
import SmoothScroller from "@/components/SmoothScroller";

export const metadata = {
  title: "Portfolio Project",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={` h-full antialiased`}>
      <body className="min-h-full flex flex-col">
        <Navbar />
        <SmoothScroller>{children}</SmoothScroller>
      </body>
    </html>
  );
}
